database:
  host: coderushoj-infra-mysql.coderushoj.svc
  port: 3306
  user: coderushoj
  password: ""
  name: code_rush_oj

rocketmq:
  name-server: "coderushoj-infra-rocketmq-namesrv.coderushoj.svc:9876"
  topic: "submission-topic" # 需要明确指定 Topic
  # producer:
  #  group: submission-producer-group # 如果需要生产者，则取消注释
  consumer:
    group: submission-consumer-group

sandbox-discovery:
  namespace: "coderushoj"
  service: "croj-sandbox"
  port-name: "http"
  refresh-interval: "5s"
  kubeconfig: ""
